name: First Workwlow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v4
      - name: Print Greeting
        run: echo "Hello World"
      - name: List files
        run: ls -la
      - name: Print GoodBye
        run: echo "Bye"
