name: First Workwlow
on: [push, workflow_dispatch]
jobs:
  get-code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Code
        uses: actions/checkout@v4
  test:
    needs: get-code
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "run our test"
      - name: List files
        run: ls -la
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building"
